### ISSUE TITLE
Include terms from "remote" scope directories

### ISSUE THREAD

**Issue by sih** [trustoverip/ctwg-toolkit-mrg#2]
### Scenario: happy path - the remote repo exists, the user has access, the MRG exists
Given a scoperef to a remote repository that exists, contains a non-empty MRG, and which the user has access
When the user generates an MRG
Then the appropriate terms should be copied from the remote repository

### Scenario: exception - the remote repo does not exist
*@RieksJ* please review to see if you agree with this behaviour (and amend if not)
Given a scoperef to a remote repository that does not exist 
When the user generates an MRG
Then the MRG should be generated from the local scope and a warning given that the remote entries could not be created

### Scenario: exception - the user does not have access to the remote repo
*@RieksJ* please review to see if you agree with this behaviour (and amend if not)
Given a scoperef to a remote repository that exists but to which the user does not have access 
When the user generates an MRG
Then the MRG should be generated from the local scope and a warning given that the remote entries could not be created

**Comment by RieksJ** [comment]
I agree with the behavior. Warnings should be precise, complete and helpful to curators for fixing stuff
