### ISSUE TITLE
Guinea-pigging MRGT - request for documenting how to enter configuration options from commandline

### ISSUE THREAD

**Issue by RieksJ** [trustoverip/ctwg-toolkit-mrg#26]
As I followed the README file to locally generate an MRG for TEv2, I ran into the problem that while I have Docker installed (I use it to do TEv1 work on eSSIF-Lab), there is not window that I can type the configuration stuff (port, mrgfilepath, github username and personal access token). Docker documentation didn't help me either. 

Is there a way to get the window, or alternatively, some commands that I can use in CMD to specify and subsequently run the container?

**Comment by sih** [comment]
Ah that's good that you have used Docker before. From your comments on the CTWG yesterday I was under the impression you hadn't used it.

You enter the window by clicking on the downward arrow by optional settings. I have added a screenshot to go along with the instructions. Please take a look.

**Comment by RieksJ** [comment]
Turns out I use a Docker version that is too old. I'll update the documentation to say you need a relative new one.
