### ISSUE TITLE
Guinea-pigging MRGT - YAML error

### ISSUE THREAD

**Issue by RieksJ** [trustoverip/ctwg-toolkit-mrg#28]
When I run the mrg generator on 
- scopedir = `https://github.com/essif-lab/framework/docs/tev2`
- saf = `saf.yaml`
- scope vsn tag = `mrgtest`

the result is as follows:

![image](https://user-images.githubusercontent.com/8522589/195110821-291925fa-2334-4a83-b3fa-b5dca00713f5.png)

However, when I run `saf.yaml` through `http://www.yamllint.com/` to check for yaml-validity, it says that the file is actually valid yaml.

**Comment by RieksJ** [comment]
Apart from this, the error message does not provide developers with clues that would have actually helped to solve the problem.

**Comment by sih** [comment]
The error is actually down to the fact that there is no SAF at the location you have input. Navigating the ESSIF repo using a browser, and then copy-pasting, the directory is actually: https://github.com/essif-lab/framework/tree/master/docs/tev2

I have added a better error message when the user has put in a directory that doesn't contain a SAF to account for these types of user error.

I have also made some changes to cater for the latest changes to terms definitions so make sure you pull the new image:

docker pull ghcr.io/trustoverip/ctwg-mrg-gen@sha256:1bc93a04c501bf487a6b8d4e0eccfc0590730f08deb8e3c31263b387406725ec
