### ISSUE TITLE
Apply term selection criteria when constructing the MRG

### ISSUE THREAD

**Issue by sih** [trustoverip/ctwg-toolkit-mrg#3]
This is the current specification for adding/removing terms to the terminology as part of [terminology construction](https://essif-lab.github.io/framework/docs/tev2/terminology-construction) (this spec and the terminology construction text should be consistent. If not, this spec takes precedence for as long as this issue is open):

* For all syntaxes specified below:
  * `:<vsntag>` is optional; if omitted, terms are selected from the ‘default’ MRG of the specified scope
  * `@<scopetag>` is optional; if omitted, the current scope is the specified scope.

* For ADDING terms from a terminology that is under construction, you can use:
  * `terms[<termslist>]@<scopetag>:<vsntag>`, where `<termslist>` is a comma-separated list of terms (to be found in the `term` field of an MRG-entry or Curated Text header).
  * `tags[<grouptagslist>]@<scopetag>:<vsntag>`, where `<grouptagslist>` is a comma-separated list of grouptags. This syntax selects every term that has any of the listed grouptags` in its `groupTags` field.
  * `*` (the asterisk character) specifies every term in the designated scope (and version).

* For REMOVING terms from a terminology that is under construction uses the following syntaxes to remove entries from terminology-under-construction (TUC):
  * `-tags [ <grouptagslist> ]````, where `<grouptagslist>` is a comma-separated list of grouptags; every term in the TUC that has one of these grouptags will be removed.
  * `-terms [ <termslist> ]````, where `<termslist>` is a comma-separated list of terms; every such term in the TUC will be removed.

Syntax for RENAMING terms from a terminology that is under construction will be deferred for now

**Comment by sih** [comment]
Proposed change of syntax for term and tag selection from @RieksJ 

* ````termslist[<term1>,<term2>,…]@<scopetag>:<vsntag>````, where:
  * ````<vsntag>```` is optional
    * if omitted, terms are selected from the ‘default’ MRG of that scope, and
  * ````<scopetag>```` is also optional
    * if omitted, terms are selected from from the current scope. 
  * This might be used for:
    * The creation of custom/specific mrgs/hrgs, e.g. to be used for generating a glossary that can be added as an appendix for a whitepaper;
    * Deselecting (that would require a `-`-sign in front of `termslist`) terms that are defined in a CText in the current scope, but are not yet matured sufficiently to warrant an export in the scope’s default MRG.

* ````tagslist[<tag1>,<tag2>,…]@<scopetag>:<vsntag>````, where:
  * ````<vsntag>```` is optional
    * If omitted, terms come from the ‘default’ mrg of that scope, and
  * ````< scopetag>```` is also optional
    * If omitted, terms come from the current scope.
  * ````<tag<i>>```` can be a:
    * Scopetag
      * Which is shorthand for `all terms in the scope` as specified by the default MRG of that scope, or `all terms for which there is a CText` if the tag is used for generating the default MRG of that scope;
    * Grouptag
      * Which is shorthand for `all terms in the scope that have the grouptag explicitly assigned`
    * Versiontag, which is shorthand for `all terms in the scope` as specified by the version of the MRG of that scope as specified by the versiontag.
    * * (the asterisk character), which is identical with specifying the scopetag for the current scope (as specified in its SAF).

**Comment by sih** [comment]
@RieksJ: 
One question, in the tags section, what happens if we have a grouptag which is the same as a scopetag? 

We would have a conflict between only selecting terms with that grouptag versus selecting all? In practice this may never happen, but in order to implement this we would still need either a "winner" (e.g. select all terms) or a rule (e.g. to raise an error where the curator had to change the tags before regeneration).

**Comment by RieksJ** [comment]
@sih Could you continue editing the first post in this thread such that it serves as the (current) specification of it all? 

Also, I suggest to change `termslist[` into `terms[` and `tagslist[` into `tags[`.

**Comment by RieksJ** [comment]
> One question, in the tags section, what happens if we have a grouptag which is the same as a scopetag?

Every tag (scopetag, grouptag, versiontag) is defined within the scope that uses it. Consequently, we may require every such tag to be unique, meaning that the set of scopetags is disjunct from that of grouptags, and they are disjunct from versiontags. We may want to let the ICTool to check whether or not this is the case.

**Comment by sih** [comment]
> > One question, in the tags section, what happens if we have a grouptag which is the same as a scopetag?
> 
> Every tag (scopetag, grouptag, versiontag) is defined within the scope that uses it. Consequently, we may require every such tag to be unique, meaning that the set of scopetags is disjunct from that of grouptags, and they are disjunct from versiontags. We may want to let the ICTool to check whether or not this is the case.

Okay, so should it happen (e.g. there is a bug in the Integrity Checking Tool that has allowed something to slip past or the ICT could not run) then the MRG should raise an exception and provide a message that it has found a duplicate in the scope. Again, this should not happen but clearly should not doesn't mean cannot!

**Comment by RieksJ** [comment]
I cannot edit your posts. However, I've started to update the documentation to include the stuff. I'll tell you when it's there, and what (I then remember that) the changes are.

You are right: <term> should be <term-id>.

I'm also adding syntax for renaming a term: `rename [<newname>](<term-id>@<scopetag>:<vsntag>)`, where `<scopetag>` is optional (default is current scope), and `:<vsntag>` is also optional (default is the 'default' version of the scope). What do you think?

**Comment by sih** [comment]
> I cannot edit your posts. However, I've started to update the documentation to include the stuff. I'll tell you when it's there, and what (I then remember that) the changes are.
> 
> You are right: should be .
> 
> I'm also adding syntax for renaming a term: `rename [<newname>](<term-id>@<scopetag>:<vsntag>)`, where `<scopetag>` is optional (default is current scope), and `:<vsntag>` is also optional (default is the 'default' version of the scope). What do you think?

Noted re. documentation update
I'm fine with the renaming syntax you have specified as it echoes the Markdown hyperlinks which I suppose is also a form of indirection!

**Comment by RieksJ** [comment]
I've changed some stuff regarding terms generation. It's become somewhat different from what we discussed. I'd like you to check  out (1) the (new) page on [terminology construction](https://essif-lab.github.io/framework/docs/tev2/terminology-construction), and (2) the (slightly) modified page on the [mrgt](https://essif-lab.github.io/framework/docs/tev2/tev2-toolbox-mrgt).

**Comment by RieksJ** [comment]
@sih Have updated the first post (yes, I've write access now) to be in line with the [terminology construction](https://essif-lab.github.io/framework/docs/tev2/terminology-construction). Still need to do the renaming syntax

**Comment by sih** [comment]
Ok great ... thanks @RieksJ

**Comment by RieksJ** [comment]
The [syntax for terminology construction](https://essif-lab.github.io/framework/docs/tev2/spec-tools/terminology-construction) has been documented. We will defer the renaming syntax until the need is expressed (e.g., as an issue in [essiflab/framework](https://github.com/essif-lab/framework/issues).

@sih if you agree, please close this issue

**Comment by sih** [comment]
Looks good @RieksJ ... I will keep this open until I have implemented the changes in the specification, but have removed you as an assignee.

Once I've made the changes I'll close this issue.
