### ISSUE TITLE
Why is the 'master' branche stale?

### ISSUE THREAD

**Issue by RieksJ** [trustoverip/ctwg-toolkit-mrg#35]
We have a `master` branche and a `develop` branche.  Usually, the master branche would be what is being published and used, but it is stale. What's going on?

**Comment by sih** [comment]
> We have a `master` branche and a `develop` branche. Usually, the master branche would be what is being published and used, but it is stale. What's going on?

That's not quite the case. Yes the master branch is what is published and used but only after the branch where features are merged to (in our case develop) has been agreed as okay. Then there is a PR to merge develop on to master. 

So develop acts as the integration branch to ensure that master has the current live code (which allows bug fixes to be done as branches off master). When you are ready with develop (probably after your README changes) then that might be a good time to merge develop on to master.

When the next lot of developers come along, they will create new feature branches and then when ready for integration testing merge on to develop. Once you have tested their changes then it can be merged back on to master.
