### ISSUE TITLE
Unable to parse SAF

### ISSUE THREAD

**Issue by Ca5e** [trustoverip/ctwg-toolkit-mrg#59]
While attempting to generate a MRG, both the SAF supplied inside the eSSIF-Lab TEv2 directory and a custom SAF raise the `UNABLE_TO_PARSE_SAF` exception _(MRGGenerationException: Generation failed: Unable to parse SAF. Check that it is valid YAML)_, without showing any more insight as to what is wrong with the file.

Based on the latest image pulled this morning _(docker pull ghcr.io/trustoverip/ctwg-mrg-gen:latest)_, I can't seem to get the generator past step 1/6.
@ryan-thorburn @brianorwhatever

**Comment by brianorwhatever** [comment]
Thanks, I am looking into getting this running past some errors as well. Was this previously working for you?

**Comment by Ca5e** [comment]
> Thanks, I am looking into getting this running past some errors as well. Was this previously working for you?

Unfortunately not. Yesterday was my first attempt at running.

**Comment by brianorwhatever** [comment]
Are you running it with docker or locally?

**Comment by Ca5e** [comment]
> Are you running it with docker or locally? I will be attempting with docker at first

Docker, following the instructions inside the [README](https://github.com/trustoverip/ctwg-toolkit-mrg#readme).

**Comment by brianorwhatever** [comment]
@Ca5e I have likely fixed your issues. Please give it another go and let me know if you think this has been resolved

**Comment by Ca5e** [comment]
> 

It seemed to work shortly after the changes you made, through the [URL](https://ctwg-toolkit-mrg-production.up.railway.app/ctwg/mrg) @RieksJ gave me. Currently however, there seems to be different error produced while using the default input values.
`Unable to generate MRG. Error was https://github.com/essif-lab/framework/tree/master/docs/tev2/saf.yaml: There is no such resource or anonymous access to this repository is not allowed.`

Using a different URL or local file doesn't seem to resolve the issue.
Also, I am not seeing an updated version of the package yet, but I assume this is because we're still testing around.

**Comment by brianorwhatever** [comment]
Apologies @Ca5e my github token had expired. It is now running with a new token that does not expire. As for the "package" with an updated docker image I have not yet created one as I'm not sure how to achieve that. Will look into it ASAP

**Comment by Ca5e** [comment]
> Apologies @Ca5e my github token had expired. It is now running with a new token that does not expire. As for the "package" with an updated docker image I have not yet created one as I'm not sure how to achieve that. Will look into it ASAP

Thanks for that! It does indeed appear to be working, so I think it's safe to close this issue.
On another note however, do you by chance have a clue as to why the MRGT runs on a spring web app instead of a CLI? I am finding some traces of a `mrg-generator` command, which would be of great help if we'd want to integrate the tool in a pipeline.

**Comment by brianorwhatever** [comment]
I was not involved with the project at that time sorry
